### ISSUE TITLE
Panic while running on github.com/prometheus/prometheus

### ISSUE THREAD

**Issue by sylr** [jlauinger/go-safer#2]
Here are the steps I followed:

```shell
$ cd ~/go/src/github.com/prometheus/prometheus
$ git checkout master
$ git pull origin master
$ go-safer ./...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x11a24f7]

goroutine 14112 [running]:
github.com/jlauinger/go-safer/passes/structcast.detectUnsafeCast(0x137a6a0, 0xc014df65c0, 0x0, 0x0, 0x0, 0x0, 0x2c3b0a00)
	/Users/s.rabot/go/src/github.com/jlauinger/go-safer/passes/structcast/structcast.go:101 +0xd7
github.com/jlauinger/go-safer/passes/structcast.structCastWithMismatchingTargetLength(0xc014df65c0, 0xc04dc9d5e0, 0x1376e00)
	/Users/s.rabot/go/src/github.com/jlauinger/go-safer/passes/structcast/structcast.go:47 +0x4b
github.com/jlauinger/go-safer/passes/structcast.run.func1(0x1376e20, 0xc014df65c0)
	/Users/s.rabot/go/src/github.com/jlauinger/go-safer/passes/structcast/structcast.go:33 +0x4e
golang.org/x/tools/go/ast/inspector.(*Inspector).Preorder(0xc04dcaa9c0, 0xc002335550, 0x1, 0x1, 0xc073d57d40)
	/Users/s.rabot/go/src/golang.org/x/tools/go/ast/inspector/inspector.go:77 +0xa2
github.com/jlauinger/go-safer/passes/structcast.run(0xc04dc9d5e0, 0xc045c44870, 0x14dd000, 0xc0300c2938, 0xc0023355c0)
	/Users/s.rabot/go/src/github.com/jlauinger/go-safer/passes/structcast/structcast.go:30 +0xcc
golang.org/x/tools/go/analysis/internal/checker.(*action).execOnce(0xc04cf41860)
	/Users/s.rabot/go/src/golang.org/x/tools/go/analysis/internal/checker/checker.go:658 +0x75f
sync.(*Once).doSlow(0xc04cf41860, 0xc002335790)
	/usr/local/go/src/sync/once.go:66 +0xec
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:57
golang.org/x/tools/go/analysis/internal/checker.(*action).exec(0xc04cf41860)
	/Users/s.rabot/go/src/golang.org/x/tools/go/analysis/internal/checker/checker.go:577 +0x65
golang.org/x/tools/go/analysis/internal/checker.execAll.func1(0xc04cf41860)
	/Users/s.rabot/go/src/golang.org/x/tools/go/analysis/internal/checker/checker.go:565 +0x34
created by golang.org/x/tools/go/analysis/internal/checker.execAll
	/Users/s.rabot/go/src/golang.org/x/tools/go/analysis/internal/checker/checker.go:571 +0x125
```

```
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/s.rabot/go/bin"
GOCACHE="/Users/s.rabot/Library/Caches/go-build"
GOENV="/Users/s.rabot/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/s.rabot/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/s.rabot/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/s.rabot/go/src/github.com/prometheus/prometheus/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/z0/rcywz4nn3jg6g96h67c_4xzdw31lvl/T/go-build826743891=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by agnivade** [comment]
Came here to report that. Just the `ok` of the type-cast needs to be checked. It's skipped in the code.

**Comment by jlauinger** [comment]
Thanks for reporting this! :sparkles:

Sorry it took so long to answer, I was super busy in the last weeks. I'll implement the `ok` check right now :+1:
